# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
 gradle(task: 'assemble', build_type: 'Release')
  upload_to_play_store(track: 'beta')
    #firebase_app_distribution(
    #        app: "1:102210530844:android:aca8ced37a00acd508b9d9",
    #        testers: "mkaan@abdcomputers.net, acrow@crowtech.com.au",
    #        #release_notes: changelog,
    #        #groups: "qa-team, dev-team"
    #        firebase_cli_path: "/usr/local/bin/firebase/cli/binary"
    #    ) 
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
